/* ==========================================================
   Open Reel – catalog logic (vanilla JS, no build step)
   1. Movie data
   2. Rendering
   3. Search filter
   4. Player dialog
   ========================================================== */

"use strict";

/* ---------- 1. Movie data ----------
   Every film lives on the Internet Archive, so one identifier
   (the last part of archive.org/details/<identifier>) is enough
   to build the poster, watch, embed and download URLs.

   TO ADD A FILM: open its page on archive.org, copy the
   identifier from the address bar, and add one line below.
   Always confirm the item's "Rights" / "Usage" field says
   Public Domain or a license that permits free sharing. */

const ARCHIVE = "https://archive.org";

function film(archiveId, title, year, director, description) {
  return {
    archiveId,
    title,
    year,
    director,
    description,
    poster: `${ARCHIVE}/services/img/${archiveId}`,   // thumbnail generated by the Archive
    watchUrl: `${ARCHIVE}/details/${archiveId}`,       // item page
    embedUrl: `${ARCHIVE}/embed/${archiveId}`,         // embeddable player
    downloadUrl: `${ARCHIVE}/download/${archiveId}`    // lists every downloadable file
  };
}

const movies = [
  film(
    "night_of_the_living_dead",
    "Night of the Living Dead",
    1968,
    "George A. Romero",
    "Strangers trapped in a Pennsylvania farmhouse face the recently dead. A landmark of horror cinema."
  ),
  film(
    "nosferatu",
    "Nosferatu",
    1922,
    "F. W. Murnau",
    "A silent-era vampire classic and an unofficial adaptation of Bram Stoker's Dracula."
  ),
  film(
    "his_girl_friday",
    "His Girl Friday",
    1940,
    "Howard Hawks",
    "A newspaper editor schemes to win back his ex-wife and star reporter in this fast-talking comedy."
  ),
  film(
    "Plan_9_from_Outer_Space_1959",
    "Plan 9 from Outer Space",
    1959,
    "Ed Wood",
    "Aliens raise the dead to stop humanity from building a doomsday weapon. A cult favourite."
  ),
  film(
    "The_Cabinet_of_Dr._Caligari_1920",
    "The Cabinet of Dr. Caligari",
    1920,
    "Robert Wiene",
    "A sleepwalker and a sinister showman in a landmark of German Expressionism."
  )
  // Add more films here, e.g.:
  // film("archive_identifier", "Title", 1931, "Director", "One-sentence summary."),
];

/* ---------- 2. Rendering ---------- */

const grid = document.getElementById("movie-grid");
const emptyState = document.getElementById("empty-state");
const resultCount = document.getElementById("result-count");
const searchInput = document.getElementById("search");

/* Build one card. Elements are created with the DOM API (not innerHTML)
   so data can never inject markup into the page. */
function createCard(movie) {
  const card = document.createElement("article");
  card.className = "card";

  // Poster (button that opens the player)
  const posterBtn = document.createElement("button");
  posterBtn.type = "button";
  posterBtn.className = "poster-btn";
  posterBtn.setAttribute("aria-label", `Watch ${movie.title}`);
  posterBtn.addEventListener("click", () => openPlayer(movie));

  const img = document.createElement("img");
  img.src = movie.poster;
  img.alt = `Poster for ${movie.title}`;
  img.loading = "lazy";
  // If the image is missing, swap in a text placeholder
  img.addEventListener("error", () => {
    const fallback = document.createElement("div");
    fallback.className = "poster-fallback";
    fallback.textContent = movie.title;
    img.replaceWith(fallback);
  });
  posterBtn.appendChild(img);

  // Text details
  const body = document.createElement("div");
  body.className = "card-body";

  const title = document.createElement("h3");
  title.textContent = movie.title;

  const year = document.createElement("p");
  year.className = "year";
  year.textContent = movie.year;

  const director = document.createElement("p");
  director.className = "director";
  director.textContent = movie.director;

  const desc = document.createElement("p");
  desc.className = "desc";
  desc.textContent = movie.description;

  // Actions
  const actions = document.createElement("div");
  actions.className = "actions";

  const watchBtn = document.createElement("button");
  watchBtn.type = "button";
  watchBtn.className = "btn btn-primary";
  watchBtn.textContent = "Watch";
  watchBtn.setAttribute("aria-label", `Watch ${movie.title}`);
  watchBtn.addEventListener("click", () => openPlayer(movie));

  const downloadLink = document.createElement("a");
  downloadLink.className = "btn";
  downloadLink.href = movie.downloadUrl;
  downloadLink.target = "_blank";
  downloadLink.rel = "noopener";
  downloadLink.textContent = "Download";
  downloadLink.setAttribute("aria-label", `Download ${movie.title}`);

  actions.append(watchBtn, downloadLink);
  body.append(title, year, director, desc, actions);
  card.append(posterBtn, body);
  return card;
}

/* Replace the grid contents with the given list of movies */
function renderMovies(list) {
  grid.replaceChildren(...list.map(createCard));

  emptyState.hidden = list.length > 0;
  resultCount.textContent =
    list.length === 1 ? "1 film" : `${list.length} films`;
}

/* ---------- 3. Search filter ---------- */

/* Case-insensitive match against title, year, director and description */
function filterMovies(query) {
  const q = query.trim().toLowerCase();
  if (!q) return movies;

  return movies.filter((m) =>
    [m.title, String(m.year), m.director, m.description]
      .join(" ")
      .toLowerCase()
      .includes(q)
  );
}

searchInput.addEventListener("input", () => {
  renderMovies(filterMovies(searchInput.value));
});

/* ---------- 4. Player dialog ---------- */

const player = document.getElementById("player");
const playerFrame = document.getElementById("player-frame");
const playerTitle = document.getElementById("player-title");
const playerClose = document.getElementById("player-close");

function openPlayer(movie) {
  playerTitle.textContent = movie.title;
  playerFrame.src = movie.embedUrl;
  player.showModal();
}

// Clearing src stops playback when the dialog closes
player.addEventListener("close", () => {
  playerFrame.src = "about:blank";
});

playerClose.addEventListener("click", () => player.close());

// Clicking the dark backdrop (outside the dialog box) also closes it
player.addEventListener("click", (event) => {
  if (event.target === player) player.close();
});

/* ---------- Start ---------- */
document.getElementById("year").textContent = new Date().getFullYear();
renderMovies(movies);
